### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by JeftaDirksen** [JeftaDirksen/PnPMonitor#1]
- [x] Monitor names
- [x] Database version
- [x] Login (e-mail authentication token > session/cookie)
- [x] Interface
- [x] Separate agent
- [x] Distributed (multiple) agents
- [x] Move Monitor->sendMailAtXFails to db
